# Generated by Django 4.1.7 on 2023-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorTecnico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=24, null=True)),
                ('cpf', models.CharField(blank=True, max_length=16, null=True)),
                ('crc', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('nome', models.CharField(blank=True, max_length=128, null=True)),
                ('qualificacao', models.CharField(blank=True, max_length=32, null=True)),
                ('razaoSocial', models.CharField(blank=True, db_column='razao_social', max_length=128, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=64, null=True)),
                ('telefone', models.CharField(blank=True, max_length=32, null=True)),
                ('uf', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'tb_contador_tecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('ativoPassivoSped', models.CharField(blank=True, db_column='ativo_passivo_sped', max_length=16, null=True)),
                ('bairro', models.CharField(blank=True, max_length=192, null=True)),
                ('cae', models.CharField(blank=True, max_length=8, null=True)),
                ('cep', models.CharField(blank=True, max_length=12, null=True)),
                ('cidade', models.CharField(blank=True, max_length=32, null=True)),
                ('cnae', models.CharField(blank=True, max_length=32, null=True)),
                ('codigo', models.CharField(blank=True, max_length=8, null=True)),
                ('codigoEmpresaMatriz', models.CharField(blank=True, db_column='codigo_empresa_matriz', max_length=8, null=True)),
                ('codigoMunicipio', models.CharField(blank=True, db_column='codigo_municipio', max_length=8, null=True)),
                ('codigoNaturezaJuridica', models.CharField(blank=True, db_column='codigo_natureza_juridica', max_length=8, null=True)),
                ('complemento', models.CharField(blank=True, max_length=64, null=True)),
                ('cpfCnpj', models.CharField(blank=True, db_column='cpf_cnpj', max_length=24, null=True)),
                ('dataArquivo', models.CharField(blank=True, db_column='data_arquivo', max_length=12, null=True)),
                ('dataCadastro', models.DateTimeField(blank=True, db_column='data_cadastro', null=True)),
                ('dataUltimoBalanco', models.DateField(blank=True, db_column='data_ultimo_balanco', null=True)),
                ('descricaoNaturezaJuridica', models.CharField(blank=True, db_column='descricao_natureza_juridica', max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('enquadramento', models.CharField(blank=True, max_length=255, null=True)),
                ('filial', models.CharField(blank=True, max_length=64, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('inscricaoEstadual', models.CharField(blank=True, db_column='inscricao_estadual', max_length=24, null=True)),
                ('inscricaoMunicipal', models.CharField(blank=True, db_column='inscricao_municipal', max_length=24, null=True)),
                ('livro_caixa', models.BooleanField(blank=True, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=64, null=True)),
                ('moduloContabilidade', models.BooleanField(blank=True, db_column='modulo_contabilidade', null=True)),
                ('nomeAbreviado', models.CharField(blank=True, db_column='nome_abreviado', max_length=16, null=True)),
                ('nomeFantasia', models.CharField(blank=True, db_column='nome_fantasia', max_length=64, null=True)),
                ('nomeRegistro', models.CharField(blank=True, db_column='nome_registro', max_length=64, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('numeroOrdem', models.CharField(blank=True, db_column='numero_ordem', max_length=8, null=True)),
                ('numeroRegistro', models.CharField(blank=True, db_column='numero_registro', max_length=8, null=True)),
                ('razaoSocial', models.CharField(blank=True, db_column='razao_social', max_length=64, null=True)),
                ('receitaDespesaSped', models.CharField(blank=True, db_column='receita_despesa_sped', max_length=16, null=True)),
                ('registro', models.CharField(blank=True, max_length=18, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('tipoInscricao', models.CharField(blank=True, db_column='tipo_inscricao', max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=255, null=True)),
                ('ufInscricao', models.CharField(blank=True, db_column='uf_inscricao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValoresDre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoValor', models.CharField(blank=True, db_column='tipo_valor', max_length=255, null=True)),
                ('margemBruta', models.DecimalField(blank=True, db_column='margem_bruta', decimal_places=2, max_digits=1000, null=True)),
                ('lucroBruto', models.DecimalField(blank=True, db_column='lucro_bruto', decimal_places=2, max_digits=1000, null=True)),
                ('faturamento', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('margemEbitda', models.DecimalField(blank=True, db_column='margem_ebitda', decimal_places=2, max_digits=1000, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('margemLiquida', models.DecimalField(blank=True, db_column='margem_liquida', decimal_places=2, max_digits=1000, null=True)),
                ('lucroLiquido', models.DecimalField(blank=True, db_column='lucro_liquido', decimal_places=2, max_digits=1000, null=True)),
                ('receitaLiquida', models.DecimalField(blank=True, db_column='receita_liquida', decimal_places=2, max_digits=1000, null=True)),
                ('dataInicial', models.DateTimeField(blank=True, db_column='data_inicial', null=True)),
                ('dataFinal', models.DateTimeField(blank=True, db_column='data_final', null=True)),
            ],
            options={
                'db_table': 'tb_valores_dre',
                'managed': False,
            },
        ),
    ]
