# Generated by Django 4.1.7 on 2023-03-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='escritorioId',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imgEsc',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nomeCompleto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nomeFantasia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nomeUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='uf',
        ),
        migrations.DeleteModel(
            name='Escritorio',
        ),
    ]
